name: library_flutter_frontend
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0 # Добавь эту строку

flutter:
  uses-material-design: true